### ISSUE TITLE
wrong insertion

### ISSUE THREAD

**Issue by dadiborn** [ryanpcmcquen/flatmap-fast#4]
on line #13 change result.push(arr) to result.push(arr[outerIndex])

**Comment by ryanpcmcquen** [comment]
Can you write a test for this?

**Comment by ryanpcmcquen** [comment]
Can you give an example of how this is an issue versus the native `flatMap`?

**Comment by dadiborn** [comment]
sorry, busy days.. here is screenshots if you will. And Happy New Year :)
![original](https://user-images.githubusercontent.com/36768799/103424940-e18acb00-4bb7-11eb-93bd-d87ae58034ea.PNG)
![yours](https://user-images.githubusercontent.com/36768799/103424942-e2236180-4bb7-11eb-9776-9d0a029ca587.PNG)

**Comment by Ryan-McLemon** [comment]
Cool @dadiborn, will you make a PR with that test and the change?

**Comment by ryanpcmcquen** [comment]
@dadiborn, have you had a chance to make a PR for this?

**Comment by ryanpcmcquen** [comment]
Closed in 4.0.1.

**Comment by ryanpcmcquen** [comment]
Thank you for the report!
